version: '3.8'

services:
  # Orthanc DICOM Server
  orthanc:
    image: orthancteam/orthanc:latest
    container_name: orthanc
    ports:
      - "8042:8042"  # Orthanc web interface
      - "4242:4242"  # DICOM port
    volumes:
      - orthanc-db:/var/lib/orthanc/db
      - ./worklists:/var/lib/orthanc/worklists:rw  # Shared worklist directory
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro  # Custom configuration file
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8042/system"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # DICOM Worklist Manager
  worklist-manager:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: worklist-manager
    ports:
      - "8092:8092"  # Worklist manager web interface
    volumes:
      - ./worklists:/app/worklists:rw  # Shared worklist directory
    environment:
      - DENO_ENV=production
      - PORT=8092
      - WORKLIST_DIR=/app/worklists
    depends_on:
      - orthanc
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  orthanc-db:
    driver: local
